### ISSUE TITLE
Few issues with New Project Setup (Face, Eye, And Body)

### ISSUE THREAD

**Issue by dilmerv** [oculus-samples/Unity-Movement#2]
Guys great work on this project I am having a lot of fun !

Few things which I believe to be problems with new projects:

Looks like there are a couple of layers not included when you create a new project and import the Movement SDK.

These layers currently need to be created manually:

- HiddenMesh
- Character
- MirroredCharacter

Now I've Body, Face, And Eye tracking enabled in the OVR Camera Rig also Android Manifest has the proper permissions. Oculus app also has all the settings to be able to run this project with Oculus Link as shown below:

![image](https://user-images.githubusercontent.com/1216121/200214112-72ce9e8f-b621-485f-8f39-32af05e5d59d.png)

Now I think body tracking may be missing from above? or is this error something different?

[OVRPlugin] [XRCMD][failure] [XR_ERROR_RUNTIME_FAILURE]: xrLocateBodyJointsFB(m_xrBodyTracker, &info, &locations), arvr\projects\integrations\ovrplugin\src\util\compositoropenxr.cpp:5217
UnityEngine.Debug:LogWarning (object)
OVRManager:OVRPluginLogCallback (OVRPlugin/LogLevel,intptr,int) (at Assets/Oculus/VR/Scripts/OVRManager.cs:1628)

The result is that I can do eye tracking and face tracking successfully but body tracking is not working at all, I have a feeling this is due to not having body tracking available through Oculus Link ? I can try to run this right after from the device to see if it works and report back with my results.

Thanks again for all you do !
Dilmer

**Comment by dilmerv** [comment]
Ok I can confirm that deploying the demo scenes to a Meta Quest Pro work with body tracking, looks like Oculus Link may not have that option within the BETA tab in the Oculus App just yet.

**Comment by dilmerv** [comment]
Ok looks like everything is working now when I deploy it to the device, I also had to use Vulkcan since the OpenGLES3 made all the materials have a magenta type color.

Thanks guys false alarm but hopefully this helps other people.

**Comment by BattleAxeVR** [comment]
Hey there, I just had this same exact issue in my branch of hello_xr via Link. What do you mean, "false alarm?" This seems very much like body tracking simply doesn't work over Link yet. 

I can't test the code yet on Android since I need to request the runtime permissions and that requires Android 12 to do it via C++ / JNI native code (there is no java code in the hello_xr sample and I don't want to bother adding it). 

But I know eye tracking works (both through Link and standalone, as expected).

**Comment by dilmerv** [comment]
@BattleAxeVR you are correct I think the main issue here is that Oculus Link doesn't provide a body tracking option, I see face expressions and eye tracking but not body tracking.

Perhaps this is not really an issue with this repo but an update needed on the Oculus / Meta App.

**Comment by sohailshafiiWk** [comment]
Hello, thank you for the comments and I'm sorry you are dealing with Link body tracking issues. We will need to investigate on your behalf to see what's going on in regards to that problem.

Also, as you pointed out we need to add some notes regarding layers that are useful for these samples.

**Comment by BattleAxeVR** [comment]
Thank you so much! I would really appreciate having body tracking working on PC VR, not just for debugging / rapid iteration but to actually ship games that use it. 

Above you can see my branch of hello_xr which reproduces this issue in C++ / OpenXR native code, where Quest over Link has a runtime error in xrLocateBodyJointsFB on PC, which returns XR_SUCCESS in standalone builds.

https://github.com/BattleAxeVR/OpenXR-SDK-Source/blob/42b78bdcb96adc27b7516b015e051d67830a6e7b/src/tests/hello_xr/openxr_program.cpp#L1432

**Comment by BattleAxeVR** [comment]
Btw, this runtime error happens on Quest 1 (in standalone mode) not just Link / AirLink on Quest 2 or Pro. I figured if Quest 1 supports Hand Tracking 2.0 via the generic hand tracking extension it might support the new body tracking. It would be really nice having all the Quest line work with this, when you get time. And on PC too.

**Comment by sohailshafiiWk** [comment]
> Btw, this runtime error happens on Quest 1 (in standalone mode) not just Link / AirLink on Quest 2 or Pro. I figured if Quest 1 supports Hand Tracking 2.0 via the generic hand tracking extension it might support the new body tracking. It would be really nice having all the Quest line work with this, when you get time. And on PC too.

Thank you for the detailed notes. We have some folks looking at this issue right now and I'll be sure to provide some updates when a resolution is found.

**Comment by BattleAxeVR** [comment]
Thank you so much! I know Meta's going through a rough time but those of us who build VR games and apps know that Meta HMDs are the majority of the market, so we're rooting for you all to succeed. At least I am. Please keep us lowly PC VR folks in mind (I do work in both areas and having the same exact code on PC as on mobile is such a time-saver and what I love about OpenXR in general, but having feature parity would be awesome. I really wish Quest 3 would have eye/face tracking too, so we can deploy games that use it for core interactivity as a base assumption, but I understand if it's too expensive for a consumer product).

**Comment by sohailshafiiWk** [comment]
> Thank you so much! I know Meta's going through a rough time but those of us who build VR games and apps know that Meta HMDs are the majority of the market, so we're rooting for you all to succeed. At least I am. Please keep us lowly PC VR folks in mind (I do work in both areas and having the same exact code on PC as on mobile is such a time-saver and what I love about OpenXR in general, but having feature parity would be awesome. I really wish Quest 3 would have eye/face tracking too, so the stuff we're building now on Pro can trickle down to consumer space next year).

Thank you for the support. We are still trying to sort the issue out and will let you know when a solution has been found.

Also, we've added some notes to our repo's Readme regarding layers, near the end of the "Getting Started" section.

**Comment by SoumyaRipan** [comment]
Hello Guys,
With the recent 1.2.1 sample and updating the layer as mentioned, body tracking works in Quest builds for my Quest-1. yeaaa

But still doesn't work over Oculus link and I get this warning 
"[OVRPlugin] [XRCMD][failure] [XR_ERROR_RUNTIME_FAILURE]: xrLocateBodyJointsFB(m_xrBodyTracker, &info, &locations), arvr\projects\integrations\ovrplugin\src\util\compositoropenxr.cpp:5217". 

It will be easier to do testing and dev stuff over link. Not sure if it's the same for other devs with the link.
If the link issue with body tracking something you guys are still fixing, please let us know once fixed.

**Comment by BattleAxeVR** [comment]
I tested Quest 1 on Android for body tracking, in standalone mode, two days ago and I was still getting that runtime error getting the body joints, for which the exact same code works fine on Quest 2 and Pro. Weird.

**Comment by Dinevir** [comment]
Same problem here with body tracking over Link on Quest 2/Pro.

**Comment by mattmerry-meta** [comment]
Hey all - again, thanks for the feedback here! With the details you provided, we were able to reproduce, root cause and fix the issue. The fix is currently in our public test channel, you can try it here: https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-rift-s/public-test-channel/

**Comment by dilmerv** [comment]
@mattmerry-meta  that's amazing thanks for the info, I will test it tomorrow. Also I noticed something happened to the shaders, my initial project was working when I reported this issue initially but today I pulled main and all the materials now have a magenta color.

**Comment by dilmerv** [comment]
Interesting @mattmerry-meta when I did the project initially I had it all done with URP, today like I mentioned on the previous messaged I pulled main and everything is magenta, however I just created a brand new project with the Standard Pipeline and the whole thing looks way better than when it was working initially with URP. I am wondering if there are bugs with URP because it clearly looks better.

![image](https://user-images.githubusercontent.com/1216121/203215640-7c15be8f-c9bd-4666-96b1-ea0a6829a1ac.png)

**Comment by Dinevir** [comment]
@dilmerv when I added Unity-Movement into my URP project all the materials were pink. So I wrote a simple script to replace them with URP materials. So in the scene where you see pink (do backup at first) run from top menu
**Custom > Convert Meta Materials To URP**
```
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

public class ConvertMetaMaterialsToURP : MonoBehaviour
{
    private static readonly List<string> ShadersToUse = new ()
    {
        "Universal Render Pipeline/Lit",
        "Universal Render Pipeline/Lit",
        "Universal Render Pipeline/Lit",
        "Universal Render Pipeline/Simple Lit"
    };
    private static readonly List<string> ShadersToReplace = new ()
    {
        "Movement/PBR (Specular)",
        "Movement/PBR (Metallic)",
        "Standard",
        "Mobile/Diffuse"
        // "Hidden/InternalErrorShader"
    };

    private static readonly int MainTex = Shader.PropertyToID("_MainTex");
    private static readonly int BaseMap = Shader.PropertyToID("_BaseMap");
    private static readonly int BlendModeMeta = Shader.PropertyToID("_Mode");
    private static readonly int BlendModeURP = Shader.PropertyToID("_Surface");


    [MenuItem("Custom/Convert Meta Materials to URP")]
    private static void ConvertMaterials()
    {
        Debug.Log("Converting materials...");
        var allMaterials = Resources.FindObjectsOfTypeAll(typeof(Material)).ToList()
            .ConvertAll(input => (Material)input);
        Debug.Log($"Initial materials count: {allMaterials.Count}");
        var materialsToConvert = new List<Material>();
        
        foreach(var materialObject in allMaterials)
        {
            if(!ShadersToReplace.Contains(materialObject.shader.name)) continue;
            Debug.Log($"Shader found: {materialObject.shader.name}  on material: {materialObject.name}");
            materialsToConvert.Add(materialObject);
        }
        Debug.Log($"Final materials count: {materialsToConvert.Count}");

        foreach(var material in materialsToConvert)
        {
            // // for debug purposes only 
            // if(material.name != "AuraEyeLashesMat")
            //     continue;
            
            var mainTexture = material.GetTexture(MainTex);
            var newShader = Shader.Find(ShadersToUse[ShadersToReplace.IndexOf(material.shader.name)]);
            if(newShader == null)
            {
                Debug.LogError("Wrong shader name: ShaderToUse");
                return;
            }

            var blendMode = -1.0f; 
            if(material.HasProperty(BlendModeMeta))
                blendMode = material.GetFloat(BlendModeMeta);
            material.shader = newShader;
            if( blendMode > 1.5)
                material.SetFloat(BlendModeURP, 1f);
            
            if(mainTexture == null) continue;
            material.SetTexture(BaseMap, mainTexture);
            Debug.Log($"Texture replaced: {mainTexture.name}");
        }
        Debug.Log("DONE!");
    }
}
```

**Comment by BattleAxeVR** [comment]
I can confirm body tracking works perfectly in native C++ / OpenXR code on Quest 1, 2, and Pro via Link or on native standalone. Thanks so much!

**Comment by dilmerv** [comment]
@MajorThom13 try this project which I confirmed that is working [https://github.com/dilmerv/MovementSDKDemos](https://github.com/dilmerv/MovementSDKDemos)

**Comment by MajorThom13** [comment]
> 

Thanks. That did it.
I did have to take URP out, and moved the samples folder to assets, but aside from that all good.
I'm glad that Oculus had the foresight to make things accessible over Link. More power.

**Comment by sohailshafiiWk** [comment]
Hello. Please try the dev branch to see if the material issue is resolved. We currently support URP versions 10.8.0 - 12.1.8. If you are using 2022, we can experiment with later versions of URP. Since this issue is focused on body tracking across link, please file new issues for Github for any other problems that you might encounter.

**Comment by dilmerv** [comment]
@sohailshafiiWk I can confirm that pulling the dev branch fixes all the issues with URP thank you

**Comment by BattleAxeVR** [comment]
@sohailshafiiWk Hi there, I had to reopen this issue on my end because after all this time, FB / Meta body tracking extension still doesn't work on PC VR and nobody over at Oculus Dev Forums is answering anyone's posts regarding OpenXR issues.

The problem is this: FB / Meta supports body tracking on PC over Link, but only via developer mode. This means you can't ship games with it. I feel like I've been wasting my time completely as it seems like Meta has no interest in ever making any of these extensions work for actual PC VR games, only for devs to iterate faster on their Android projects. I was told this is exactly the main reason for Link's continued existence by a Dev Rel during a job interview at FB / Meta, that PC is basically an afterthought and you aren't expected to make games for it anymore, and they will offer no real support. I appreciate that you fixed this to work on PC but leaving it in limbo like this, gatekeeping all these platform features behing developer mode, is simply unacceptable. If this situation doesn't change I can't justify purchasing or using any Meta headsets from now on. It is simply unacceptable to waste my time, and many other devs' time, with such needless frustrations and limits imposed upon PC VR use. 

The hand tracking and eye tracking extensions also don't work on PC (only social eye tracking but also, only in dev mode). I refunded my Quest Pro after developing on it for three months because there were no responses to multiple requests to review that this be enabled. I'm not expecting something to be done immediately, just to know whether it WILL be done eventually. Because hand tracking's been available for Quest standalone apps for years now, but still not accessible on PC due to the aforementioned developer mode requirement. I would appreciate someone could escalate this and give us PC VR devs some clarity about whether we are wasting out time developing OpenXR functionality for headsets we paid good money for.  

Thank you for listening and I would appreciate some help on this. As would every single other member of the PC VR dev community on the Oculus dev forums, I imagine.

https://github.com/BattleAxeVR/OpenXR-SDK-Source/issues/3

**Comment by lkirkbarker** [comment]
Thank you for you comment.  We understand the importance of PCVR to our developers and are working to address some of the gaps like the ones you have highlighted.  Please stay tuned and continue to provide feedback.

**Comment by lkirkbarker** [comment]
Thank you for you comment.  We (at Meta) understand the importance of PCVR to our developers and are working to address some of the gaps like the ones you have highlighted.  Please stay tuned and continue to provide feedback.

**Comment by BattleAxeVR** [comment]
@lkirkbarker hi there, I was just wondering if you had any updates about dev-mode requirement. I asked around and nobody knows (or will tell me).

If the corporate strategy is to keep PC VR as a "dev only" device, putting it in the corner so-to-speak, I'd like to know finally so I can focus my efforts elsewhere. As it is, there was a huge scare yesterday about end-users having their dev accounts closed down so they won't be able to use hand tracking or eye-tracking (for dynamic foveated rendering) in PC VR games like Microsoft Flight Simulator or DCS, through OpenXR. It really is an untenable situation here, as I can't even decide whether it's wise to re-purchase a Quest Pro for eye-tracking development until this issue is sorted out. I am not worried about dev mode myself, but my customers, for whom it seems like Meta can pull the rug out from under their feet and suddenly eye-tracking would stop working entirely and the framerate would tank. 

In my path tracing PC VR engine, DFR can double or even triple the framerate. And body tracking feature is also super important to eliminate head-oriented locomotion sim sickness. 

If this isn't the right place to raise these issues, what is? I tried posting this on the dev forums at Oculus but it seems to be falling on deaf years. For three years already! I appreciate the fix for these features to actually work over AirLink but the bug isn't really "closed" due to requiring a dev account, is it. It makes no sense to me to gatekeep PC VR games from using Quest features that work perfectly well over Link/AirLink but for the developer account requirement which is a nuisance and a big risk for devs like me, as it could be removed at any time for people who aren't actually real devs. Yesterday was a wakeup call (even though it was a false alarm) that this should be escalated. I wish Carmack were still CTO because I could have reached out to him (again) to get this issue resolved finally. Everyone else I talk to seem to be giving us PC VR devs the runaround.

**Comment by Extrys** [comment]
> Hey all - again, thanks for the feedback here! With the details you provided, we were able to reproduce, root cause and fix the issue. The fix is currently in our public test channel, you can try it here: https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-rift-s/public-test-channel/

Not working for me yet. a friend in the same project with the same settings is working for him, what do i need to check for it to work, it never worked for me

**Comment by Extrys** [comment]
> > > Hey all - again, thanks for the feedback here! With the details you provided, we were able to reproduce, root cause and fix the issue. The fix is currently in our public test channel, you can try it here: https://www.meta.com/help/quest/articles/headsets-and-accessories/oculus-rift-s/public-test-channel/
> > 
> > 
> > Not working for me yet. a friend in the same project with the same settings is working for him, what do i need to check for it to work, it never worked for me
> 
> Hello @Extrys, Please open a new issue with details of the specific issue that you are encountering so that we can try and duplicate and assist. Thanks.

Done thanks #54
