### ISSUE TITLE
Is this sdk for real user or unity-made 3p character

### ISSUE THREAD

**Issue by hyeonmin11** [oculus-samples/Unity-Movement#28]
Hi. I love this meta movement sdk. I try to use it with my project. Comparing this video(https://www.youtube.com/watch?v=T8sYk2rwmcs) with content of this link(https://developer.oculus.com/documentation/unity/move-body-tracking/), even though the video shows that this sdk can be used for real user body tracking who wears meta quest2,  I think the content of the document means this sdk is for unity 3p character not for oculus quest2 user. Is it right? Or this sdk also can be used with real user wearing the meta quest2?

**Comment by sohailshafiiWk** [comment]
Hello. Body Tracking is used to follow the user’s position in real time.  This information can be used to track positions for applications such as fitness, or it can be used to drive a character so that others can see your movement. These characters can be retargeted to the Unity Humanoid rig which allows it to interact with key frame animations.

**Comment by sohailshafiiWk** [comment]
Closing for now. Please let us know if you need additional assistance.
