### ISSUE TITLE
Assertion failure. Value was false.

### ISSUE THREAD

**Issue by ZephyrSterling** [oculus-samples/Unity-Movement#31]
Hi!
I have used Movement for a few days. Most of the time all the scenes worked well.  But sometimes i got this error:
![fe856a3d136b7e9f4826eda70ebd2cd](https://github.com/oculus-samples/Unity-Movement/assets/141754637/3fddd948-277b-4387-895f-e72a8b29125c)
I try to find what's wrong, and it seems that the boneid is always Invalid. But the error can be eliminated by restarting Unity and Quest link. 
My relevant settings:

1. Unity 2021.3.23f1
2. XR Plug-in: Oculus
3. Oculus Integration 53.1

Could you plz help me?

**Comment by sohailshafiiWk** [comment]
We are sorry that you are encountering this issue. We are currently looking into the problem and will report back on this once we find a solution.

**Comment by TheWiselyBearded** [comment]
Hi @sohailshafiiWk , despite pulling the latest changes to this repository, the issue seems to persist. 
I'm using Oculus Integration v56 (though I've tried 50-55 as well) and the headset is on v57. None of the sample scenes run, issuing the similar warning message from OP (attached screenshot). Interestingly, when opening a scene from Oculus Integrations, say Hands Interactables, the hand tracking works fine. However, for any scene from the Movement SDK, none of the body parts track. 

Is there any way I can help further isolate this issue? A month ago when I first experienced it, I suspected it was the OS (v56 at the time and Oculus Integrations v55). However, it seems that despite OS and SDK updates, the Movement SDK is still at fault rendering the headset unusable in Unity. 

![image](https://github.com/oculus-samples/Unity-Movement/assets/15572394/bb32b558-d487-4748-a12b-edb39feb15bd)

**Comment by sohailshafiiWk** [comment]
Hello. To make sure we understand, are these problems only being encountered over Link? Do they occur if you build and load an APK? After going through https://developer.oculus.com/documentation/unity/unity-link/#settings-for-development-over-link-and-troubleshooting-steps, does the editor render anything into the HMD over link?

**Comment by TheWiselyBearded** [comment]
Hey, so yes it renders all scenes over Air Link in the headset. However, it doesn't track any body parts. Further, it fails on every build, which is partly why I've focused on in-editor for now. Apologies for not being more specific there.

Regarding the link, in the oculus PC software there is no longer a section to toggle movement tracking in the Settings. Beyond that, I've followed all other specifications.

**Comment by sohailshafiiWk** [comment]
Please try the OculusLogGather tool as specified in https://developer.oculus.com/documentation/unity/unity-link/#link-log-gathering-from-unity-editor-and-oculusloggather-tool to gather information. Perhaps upload to Google Drive if that works.

**Comment by TheWiselyBearded** [comment]
@sohailshafiiWk , thank you for your patience and help. I uploaded the log files [here](https://drive.google.com/drive/folders/1ewZ1NZVoyqkaPT47_Z0NYfsoj6jgc9Jt?usp=sharing)

**Comment by sohailshafiiWk** [comment]
> over Air Link in the headset. However, it doesn't track any body parts. Further, it fails on every build, which is partly why I've focused on in-editor for now. Apologies for not being more specific there.
> 
> Regarding the link, in the oculus PC software there is no longer a section to toggle movement tracking in the Settings. Beyond that, I've followed all other specifications.

Have you tried signing up as a developer? In case you have not, please see https://developer.oculus.com/sign-up/. Also you'll need to create an org as seen in https://developer.oculus.com/documentation/native/android/mobile-device-setup/

**Comment by TheWiselyBearded** [comment]
Hey, I already have a developer account and an organization associated with my account. I just double checked. Further, I know its not an issue with my hardware, because all apps that utilize facial tracking continue to work. Are there any other steps we can troubleshoot here? Is there a specific version of Unity and the associated SDKs that is tested and verified to work?

**Comment by sohailshafiiWk** [comment]
We are glad that you were able to resolve the issue. Please let us know if anything else comes up.

**Comment by sohailshafiiWk** [comment]
The original assertion failure should be mitigated in the v57 SDK available here: https://developer.oculus.com/downloads/package/unity-integration. We are closing this issue for now. Please let us know if the same error re-appears.

**Comment by FabienDanieau** [comment]
Hi,

I've the same issue with Unity2022.3.13f (also Unity2022.3.20f) and Unity Meta Pacakages v60.0.0

![image](https://github.com/oculus-samples/Unity-Movement/assets/1244753/aeff5cc5-305e-43d4-9160-92b37c1c1f14)

**Comment by FabienDanieau** [comment]
Got it. My link was not properly configured: https://developer.oculus.com/documentation/unity/unity-link/

**Comment by andkim-meta** [comment]
Hello, we are glad that you were able to resolve the issue. If you run into any additional problems, please create a new issue with detailed information.
