### ISSUE TITLE
Retargeting Issue with Deformations and Contraints

### ISSUE THREAD

**Issue by karunateam** [oculus-samples/Unity-Movement#66]
We are trying to use full body tracking with a custom avatar. Everything looks good in-editor when reviewing the Avatar Mapping tab and all of the animations in the Muscles & Settings tab look good. When we run on the Quest 3, we are experiencing strange placements of some of the bones and mesh. Namely, the shoulders are pushed back from their sockets, the chest and stomach are indented, and the hips seem to be dropped.

Retargeting documentation is very sparse and the code is poorly documented. There is no clear explanation of what the various forms of deformation do, how RetargetingLayer works, etc.

Is there any good source of information for us to look at?

Here are a few screenshots showing the problem areas: shoulders pushed back, indented stomach, lowered hips.

![c7fdb316d2c141c197eade2b0945c4c9](https://github.com/oculus-samples/Unity-Movement/assets/50753584/251946f5-439d-4e77-84ae-784aa916622c)
![cef4dee596df452f81c0088db4eb7086](https://github.com/oculus-samples/Unity-Movement/assets/50753584/de9602cd-ac05-4b80-a244-57c34e87a364)

**Comment by andkim-meta** [comment]
The issues that you are seeing is due to differences in the body tracking skeleton and how your character is rigged.  We have introduced weights and sliders in our deformation logic to impact different body areas. Specifically, for the shoulder issue, please look at modifying the weights under the "Shoulders" section in Full Body Deformation. For the hips, stomach, and chest areas, please look at modifying the weights such as the "Original Spine Positions Weight" under the "Body" section in Full Body Deformation. These settings are documented in more detail here: https://developer.oculus.com/documentation/unity/move-body-tracking/#setting-up-a-character-for-body-tracking, and are available in v5.0.0 release of the package.

**Comment by ratmat2002** [comment]
@andkim-meta I have updated to the v5.0.1 release and am still having a lot of trouble understanding how to modify the deformations to make our avatar look correct. Would it be possible to send you a copy of our sample project and have you provide feedback as to the necessary adjustments?

**Comment by andkim-meta** [comment]
Hello. If you could provide just the FBX file, we can take a look to check on the issues you are seeing with the automatic retargeting and deformation.

**Comment by ratmat2002** [comment]
Hello, here is the FBX file for our Avatar.

Any feedback on how we can best configure the automatic retargeting and
deformation would be greatly appreciated!

Thank you,

Andy Riedel
CTO
karunalabs.com

**Comment by ratmat2002** [comment]
Hello, here is the FBX file for our Avatar.

Any feedback on how we can best configure the automatic retargeting and
deformation would be greatly appreciated!

https://www.dropbox.com/scl/fi/w9hgotftyqmv1s54nqou0/CORE_Avatar_G.fbx?rlkey=4sozr0eqph0654z4zgwl5ck3s&st=9sg8e19v&dl=0

Thank you,

Andy Riedel
CTO
karunalabs.com

**Comment by sohailshafiiWk** [comment]
Hello,

We've made some changes recently that might help you. Please try the dev branch as of commit (https://github.com/oculus-samples/Unity-Movement/commit/24cc82f6fed296b722d2a062221eaf237d0a0f2d), with the following settings on FullBodyDeformationConstraint:

1. Original spine positions 0.5. This weight interpolates between the body tracking spine positions and the original model's (local) spine positions. Reduce spine lower and upper alignment weights to 0, and chest alignment weight to 0.
2. Shoulder roll weight can be set to 0.5 or higher. Each shoulder's position is corrected by the deformation constraint, and its rotation need to be corrected to match its child position. Increasing this value will apply this correction and in your model's case, rotate the shoulders forward so that the deltoids should not be too far backward.

Let us know if those parameters help or not
