### ISSUE TITLE
Fingers alignment in MovementRetargeting sample.

### ISSUE THREAD

**Issue by dledents** [oculus-samples/Unity-Movement#82]
Hello. In the MovementRetargeting sample, I have observed that the fingers are misaligned, with the pinky and ring fingers being particularly problematic. This misalignment leads to intersections between the fingers, especially noticeable when the fingers are clenched into a fist. Are there any way for improving it?

https://github.com/user-attachments/assets/2a4ee2d5-dee0-48b5-b165-8727dd1b7c65

**Comment by andkim-meta** [comment]
Hello. By default, the positions of the retargeted fingers are not aligned with the positions of the tracked fingers. This is due to the differences in hand proportions between the character model and the user. The alignment can be controlled using the "Finger Position Correction Weight" setting in the RetargetingProcessorCorrectBones located in the RetargetingProcessors array in the RetargetingLayer. In addition, adjustments to the hands and fingers can be made inside of the Adjustments array in the RetargetingLayer as well. If you are looking to have positions of the retargeted fingers aligned with the tracked positions, we recommend taking a look at the ISDK sample where this configuration is set.

**Comment by dledents** [comment]
Thank you for the response. Setting "Finger Position Correction Weight" improves fingers alignment.
