### ISSUE TITLE
FullBody + Multiplayer

### ISSUE THREAD

**Issue by Robostep21** [oculus-samples/Unity-Movement#83]
Im posting issue second time, because I need a step-by-step tutorial.

Im using Unity 2021.3.29f1, Photon Fusion2, Meta Interaction SDK, and this package(Meta Movement).

![изображение_2024-08-07_165432426](https://github.com/user-attachments/assets/7b3d7fbd-0e49-40b7-b000-237ee398dc0a)

I need help.

**Comment by andkim-meta** [comment]
Hello, please refer to the response given previously for setting up multiplayer (https://github.com/oculus-samples/Unity-Movement/issues/81). Since a multiplayer implementation will depend on your use case, we would recommend looking going through general networking tutorials along with the advice provided in the last response. As a friendly reminder, this issues page is primarily intended for reporting bugs or problems with the package or documentation, rather than requesting new features.

**Comment by Robostep21** [comment]
Okay, thanks.

**Comment by Robostep21** [comment]
Accidentally closed the error.

**Comment by smittenz** [comment]
Did you ever get this working the support they provided in issue #81 is really indecipherable.
